{
    "swagger": "2.0",
    "info": {
    "version": "1.0.0",
    "title": "REST API BIENES_RAICES",
    "description": "<html><body>Documentacion del proyecto <b>Bines_Raices</b> </body></html>",
    "license": {
    "name": "MIT",
    "url": "https://opensource.org/licenses/MIT"
    }
    },
    "host": "localhost:3000",
    "basePath": "",
    "tags": [
        {
            "name": "Usuarios",
            "description": "API para obtener información de los usuarios de Bienes_raices"
        },
        {
            "name": "Vendedores",
            "description": "API para obtener información de los Vendedores que trabajan en Bienes_raices"
        },
        {
            "casas": "Casas",
            "description": "API para obtener información sobre las casas en Bienes_raices"
        },
        {
            "Nosotros": "Nosotros",
            "description": "API para obtener información de la empresa Bienes_raices"
        },
        {
            "Ventas": "Ventas",
            "description": "API para realizar la venta de una propiedad de la empresa Bienes_raices"
        }
    ],
    "schemes": [
        "https"
    ],
    "consumes":[
        "application/json"
    ],
    "produces" :[
        "application/json"
    ],
    "paths":
    {
        "/api/usuarios/mostrarUsuarios/":
        {
            "get": {
                "tags": ["Usuarios"],
                "summary": "Listado de todos los usuarios que existen de Bienes_raices",
                "description": "<p>Servicio que devuelve la información detallada de todos los usuarios que existen de Bienes_raices</p><p>&nbsp;</p><p><em><strong>¿Cuáles son los usuarios existentes de Bienes_raices?</strong></em></p>",
                "responses": 
                {
                    "200":
                    {
                        "description": "OK",
                        "examples":
                        {
                            "application/json": [
                                {
                                    "id": 1,
                                    "nombre": "Leonardo",
                                    "telefono": "9531555416",
                                    "correo": "leo@gmail.com",
                                    "contraseña": "leo1234"
                                },
                                {
                                    "id": 2,
                                    "nombre": "Andres López",
                                    "telefono": "9531555416",
                                    "correo": "andres@gmail.com",
                                    "contraseña": "and5678"
                                }
                            ]
                        },
                        "schema":
                        {
                            "$ref": "#/definitions/usuarios"
                        }
                    },
                    "403":
                    {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/usuarios/crearUsuario/":
        {
            "post":
            {
                "summary":"Agrega un usuario en Bienes_raices  .",
                "operationId": "create",
                "produces": 
                [
                    "application/json"
                ],
                "parameters":
                [
                    {
                        "name": "Usuario",
                        "in": "body",
                        "description": "Usuario a agregar.",
                        "required": true,
                        "schema":
                        {
                            "$ref" : "#/definitions/NuevoUsuario"
                        }
                    }
                ],
                "tags": ["Usuarios"],
                "responses":
                {
                    "201": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/usuarios/mostrarUsuario/{id}":
        {
            "get": {
                "tags": ["Usuarios"],
                "summary": "Ver un usuario de Bienes_raices",
                "description": "<p>Servicio que que permite ver un usuario de Bienes_raices</p><p>&nbsp;</p><p><em><strong>¿Cómo agregar un nuevo usuario de Bienes_raices?</strong></em></p>",
                "responses": 
                {
                    "200":
                    {
                        "description": "OK",
                        "examples":{
                            "application/json":
                            [
                                {
                                    "id": 3,
                                    "nombre":"Juan Perez",
                                    "telefono": "9531555416",
                                    "correo": "juan@gmail.com",
                                    "contraseña": "1234"
                                }
                            ]
                        },
                        "schema":{
                            "$ref": "#/definitions/usuario"
                        }
                    },
                    "403":
                    {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id del usuario",
                        "type": "number",
                        "default": 1
                    }
                ]
            }
        },
        "/api/usuarios/actualizarUsuario/{id}":
        {
            "put":
            {
                "summary":"Modifica un usuario de Bienes_raices",
                "operationId": "update",
                "consumes":
                [
                    "application/json"
                ],
                "produces": 
                [
                    "application/json"
                ],
                "parameters":
                [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id del usuario",
                        "required": true,
                        "default": 10
                    },
                    {
                        "name": "Usuario",
                        "in": "body",
                        "description": "Usuario a modificar.",
                        "required": true,
                        "schema":
                        {
                            "$ref" : "#/definitions/NuevoUsuario"
                        }
                    }
                ],
                "tags": ["Usuarios"],
                "responses":
                {
                    "201": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/usuarios/eliminarUsuario/{id}":
        {
            "delete": {
                "tags": ["Usuarios"],
                "summary": "Eliminar un usuario de bienes_raices",
                "description": "<p>Servicio que elimina un usuario de Bienes_raices</p> <p>&nbsp;</p> <p><em><strong>¿Como eliminar un usuario de Bienes_raices?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id del usuario a eliminar.",
                        "type": "number",
                        "default": "4"
                    }
                ]
            }
        },




        "/api/vendedores/mostrarVendedores/":
        {
            "get": {
                "tags": ["Vendedores"],
                "summary": "Listado de todos los Vendedores que existen de Bienes_raices",
                "description": "<p>Servicio que devuelve la información detallada de todos los Vendedores que existen de Bienes_raices</p><p>&nbsp;</p><p><em><strong>¿Cuáles son los Vendedores existentes de Bienes_raices?</strong></em></p>",
                "responses": 
                {
                    "200":
                    {
                        "description": "OK",
                        "examples":
                        {
                            "application/json": [
                                {
                                    "id": 1,
                                    "nombre": "Leonardo",
                                    "telefono": "9531555416",
                                    "correo": "leo@gmail.com",
                                    "contraseña": "leo1234"
                                },
                                {
                                    "id": 2,
                                    "nombre": "Andres López",
                                    "telefono": "9531555416",
                                    "correo": "andres@gmail.com",
                                    "contraseña": "and5678"
                                }
                            ]
                        },
                        "schema":
                        {
                            "$ref": "#/definitions/vendedores"
                        }
                    },
                    "403":
                    {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/vendedores/crearVendedor/":
        {
            "post":
            {
                "summary":"Agrega un vendedores en Bienes_raices  .",
                "operationId": "create",
                "produces": 
                [
                    "application/json"
                ],
                "parameters":
                [
                    {
                        "name": "Vendedores",
                        "in": "body",
                        "description": "Vendedor a agregar.",
                        "required": true,
                        "schema":
                        {
                            "$ref" : "#/definitions/NuevoVendedor"
                        }
                    }
                ],
                "tags": ["Vendedores"],
                "responses":
                {
                    "201": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/vendedores/mostrarVendedor/{id}":
        {
            "get": {
                "tags": ["Vendedores"],
                "summary": "Ver un vendedor de Bienes_raices",
                "description": "<p>Servicio que que permite ver un vendedores de Bienes_raices</p><p>&nbsp;</p><p><em><strong>¿Cómo agregar un nuevo vendedores de Bienes_raices?</strong></em></p>",
                "responses": 
                {
                    "200":
                    {
                        "description": "OK",
                        "examples":{
                            "application/json":
                            [
                                {
                                    "id": 3,
                                    "nombre":"Juan Perez",
                                    "telefono": "9531555416",
                                    "correo": "juan@gmail.com",
                                    "contraseña": "1234"
                                }
                            ]
                        },
                        "schema":{
                            "$ref": "#/definitions/vendedor"
                        }
                    },
                    "403":
                    {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id del vendedor",
                        "type": "number",
                        "default": 1
                    }
                ]
            }
        },
        "/api/vendedores/actualizarVendedor/{id}":
        {
            "put":
            {
                "summary":"Modifica un vendedor de Bienes_raices",
                "operationId": "update",
                "consumes":
                [
                    "application/json"
                ],
                "produces": 
                [
                    "application/json"
                ],
                "parameters":
                [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id del vendedor",
                        "required": true,
                        "default": 10
                    },
                    {
                        "name": "Usuario",
                        "in": "body",
                        "description": "Vendedor a modificar.",
                        "required": true,
                        "schema":
                        {
                            "$ref" : "#/definitions/NuevoVendedor"
                        }
                    }
                ],
                "tags": ["Vendedores"],
                "responses":
                {
                    "201": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/vendedores/eliminarVendedor/{id}":
        {
            "delete": {
                "tags": ["Vendedores"],
                "summary": "Eliminar un vendedor de bienes_raices",
                "description": "<p>Servicio que elimina un usuario de Bienes_raices</p> <p>&nbsp;</p> <p><em><strong>¿Como eliminar un vendedor de Bienes_raices?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id del vendedor a eliminar.",
                        "type": "number",
                        "default": "4"
                    }
                ]
            }
        },

        

        "/api/casas/mostrarCasas/":
        {
            "get": {
                "tags": ["Casas"],
                "summary": "Listado de todas las Casas y departamentos que existen de Bienes_raices",
                "description": "<p>Servicio que devuelve la información detallada de todas las Casas y departamentos que existen de Bienes_raices</p><p>&nbsp;</p><p><em><strong>¿Cuáles son todas las Casas y departamentos existentes de Bienes_raices?</strong></em></p>",
                "responses": 
                {
                    "200":
                    {
                        "description": "OK",
                        "examples":
                        {
                            "application/json": [
                                {
                                    "id": 3,
                                    "precio":"16367347",
                                    "baños": "2",
                                    "habitaciones": "4",
                                    "descripcion": "Proin consequat viverra sapien, malesuada tempor tortor feugiat vitae. In dictum felis et nunc aliquet molestie"
                                },
                                {
                                    "id": 4,
                                    "precio":"16367347",
                                    "baños": "3",
                                    "habitaciones": "5",
                                    "descripcion": "Proin consequat viverra sapien, malesuada tempor tortor feugiat vitae. In dictum felis et nunc aliquet molestie"
                                }
                            ]
                        },
                        "schema":
                        {
                            "$ref": "#/definitions/casas"
                        }
                    },
                    "403":
                    {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/casas/crearCasa/":
        {
            "post":
            {
                "summary":"Agrega una casa o departamento en Bienes_raices  .",
                "operationId": "create",
                "produces": 
                [
                    "application/json"
                ],
                "parameters":
                [
                    {
                        "name": "Casas",
                        "in": "body",
                        "description": "Casa a agregar.",
                        "required": true,
                        "schema":
                        {
                            "$ref" : "#/definitions/NuevaCasa"
                        }
                    }
                ],
                "tags": ["Casas"],
                "responses":
                {
                    "201": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/casas/mostrarCasa/{id}":
        {
            "get": {
                "tags": ["Casas"],
                "summary": "Ver una casa de Bienes_raices",
                "description": "<p>Servicio que que permite ver una casa de Bienes_raices</p><p>&nbsp;</p><p><em><strong>¿Cómo agregar una nueva casa de Bienes_raices?</strong></em></p>",
                "responses": 
                {
                    "200":
                    {
                        "description": "OK",
                        "examples":{
                            "application/json":
                            [
                                {
                                    "id": 3,
                                    "precio":"16367347",
                                    "baños": "2",
                                    "habitaciones": "4",
                                    "descripcion": "Proin consequat viverra sapien, malesuada tempor tortor feugiat vitae. In dictum felis et nunc aliquet molestie"
                                }
                            ]
                        },
                        "schema":{
                            "$ref": "#/definitions/casa"
                        }
                    },
                    "403":
                    {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id de la casa",
                        "type": "number",
                        "default": 1
                    }
                ]
            }
        },
        "/api/casas/actualizarCasa/{id}":
        {
            "put":
            {
                "summary":"Modifica una casa de Bienes_raices",
                "operationId": "update",
                "consumes":
                [
                    "application/json"
                ],
                "produces": 
                [
                    "application/json"
                ],
                "parameters":
                [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id de la casa",
                        "required": true,
                        "default": 10
                    },
                    {
                        "name": "Casa",
                        "in": "body",
                        "description": "Casa a modificar.",
                        "required": true,
                        "schema":
                        {
                            "$ref" : "#/definitions/NuevoVendedor"
                        }
                    }
                ],
                "tags": ["Casas"],
                "responses":
                {
                    "201": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/casas/eliminarCasa/{id}":
        {
            "delete": {
                "tags": ["Casas"],
                "summary": "Eliminar una Casa de bienes_raices",
                "description": "<p>Servicio que elimina una casa de Bienes_raices</p> <p>&nbsp;</p> <p><em><strong>¿Como eliminar una casa de Bienes_raices?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id de la casa a eliminar.",
                        "type": "number",
                        "default": "4"
                    }
                ]
            }
        },

        

        "/api/nosotros/mostrarNosotros/":
        {
            "get": {
                "tags": ["Nosotros"],
                "summary": "Informacion sobre la empresa de Bienes_raices",
                "description": "<p>Servicio que devuelve la información detallada de la empresa Bienes_raices</p><p>&nbsp;</p><p><em>",
                "responses": 
                {
                    "200":
                    {
                        "description": "OK",
                        "examples":
                        {
                            "application/json": [
                                {
                                    "id": 1,
                                    "nombre": "Bienes Bienes",
                                    "ubicacion": "calle tepeyac #2 colonia los presidentes",
                                    "correo": "bienes_raices@gmail.com",
                                    "director": "ronaldo roque hernandez",
                                    "descripcion": "Proin consequat viverra sapien, malesuada tempor tortor feugiat vitae. In dictum felis et nunc aliquet molestie."
                                }
                            ]
                        },
                        "schema":
                        {
                            "$ref": "#/definitions/nosotros"
                        }
                    },
                    "403":
                    {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/nosotros/actualizarNosotros/{id}":
        {
            "put":
            {
                "summary":"Modifica la informacion de la empresa Bienes_raices",
                "operationId": "update",
                "consumes":
                [
                    "application/json"
                ],
                "produces": 
                [
                    "application/json"
                ],
                "parameters":
                [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id de la empresa",
                        "required": true,
                        "default": 10
                    },
                    {
                        "name": "Nosotros",
                        "in": "body",
                        "description": "empresa a modificar.",
                        "required": true,
                        "schema":
                        {
                            "$ref" : "#/definitions/NuevoNosotros"
                        }
                    }
                ],
                "tags": ["Nosotros"],
                "responses":
                {
                    "201": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        }


    },
    "definitions":
    {
        "usuario":
        {
            "type": "object",
            "properties":
            {
                "id":
                {
                    "type": "number",
                    "description": "Codigo unico que permite identificar al usuario."
                },
                "nombre":
                {
                    "type": "string",
                    "description": "Guarda el nombre del usuario."
                },
                "telefono":
                {
                    "type": "string",
                    "description": "Guarda el telefono del usuario."
                },
                "correo":
                {
                    "type": "string",
                    "description": "Guarda el correo del usuario."
                },
                "contraseña":
                {
                    "type": "string",
                    "description": "Guarda la contraseña del usuario."
                }
            }
        },
        "usuarios":
        {
            "type": "array",
            "items":
            {
                "$ref": "#/definitions/usuario"
            }
        },
        "NuevoUsuario":
        {
            "type": "object",
            "properties":
            {
                "nombre":
                {
                    "type": "string",
                    "description": "Guarda el nombre del usuario."
                },
                "telefono":
                {
                    "type": "string",
                    "description": "Guarda el telefono del usuario."
                },
                "correo":
                {
                    "type": "string",
                    "description": "Guarda el correo del usuario."
                },
                "contrasenia":
                {
                    "type": "string",
                    "description": "Guarda la contraseña del usuario."
                }
            }
        },

        "vendedor":
        {
            "type": "object",
            "properties":
            {
                "id":
                {
                    "type": "number",
                    "description": "Codigo unico que permite identificar al vendedor."
                },
                "nombre":
                {
                    "type": "string",
                    "description": "Guarda el nombre del vendedor."
                },
                "telefono":
                {
                    "type": "string",
                    "description": "Guarda el telefono del vendedor."
                },
                "correo":
                {
                    "type": "string",
                    "description": "Guarda el correo del vendedor."
                },
                "contraseña":
                {
                    "type": "string",
                    "description": "Guarda la contraseña del vendedor."
                }
            }
        },
        "vendedores":
        {
            "type": "array",
            "items":
            {
                "$ref": "#/definitions/vendedor"
            }
        },
        "NuevoVendedor":
        {
            "type": "object",
            "properties":
            {
                "nombre":
                {
                    "type": "string",
                    "description": "Guarda el nombre del vendedor."
                },
                "telefono":
                {
                    "type": "string",
                    "description": "Guarda el telefono del vendedor."
                },
                "correo":
                {
                    "type": "string",
                    "description": "Guarda el correo del vendedor."
                },
                "contraseña":
                {
                    "type": "string",
                    "description": "Guarda la contraseña del vendedor."
                }
            }
        },

        "casa":
        {
            "type": "object",
            "properties":
            {
                "id":
                {
                    "type": "number",
                    "description": "Codigo unico que permite identificar al vendedor."
                },
                "precio":
                {
                    "type": "number",
                    "description": "Guarda el precio de la casa."
                },
                "baños":
                {
                    "type": "number",
                    "description": "Guarda la cantidad de baños."
                },
                "habitaciones":
                {
                    "type": "number",
                    "description": "Guarda la cantidad de habitaciones."
                },
                "descripcion":
                {
                    "type": "string",
                    "description": "Guarda una descripcion de la casa."
                }
            }
        },

        "casas":
        {
            "type": "array",
            "items":
            {
                "$ref": "#/definitions/vendedor"
            }
        },
        "NuevaCasa":
        {
            "type": "object",
            "properties":
            {
                "id":
                {
                    "type": "number",
                    "description": "Codigo unico que permite identificar al vendedor."
                },
                "precio":
                {
                    "type": "number",
                    "description": "Guarda el precio de la casa."
                },
                "baños":
                {
                    "type": "number",
                    "description": "Guarda la cantidad de baños."
                },
                "habitaciones":
                {
                    "type": "number",
                    "description": "Guarda la cantidad de habitaciones."
                },
                "descripcion":
                {
                    "type": "string",
                    "description": "Guarda una descripcion de la casa."
                }
            }
        },

        "Nosotros":
        {
            "type": "array",
            "items":
            {
                "$ref": "#/definitions/nosotros"
            }
        },

        "NuevoNosotros":
        {
            "type": "object",
            "properties":
            {
                "id":
                {
                    "type": "number",
                    "description": "Codigo unico que permite identificar la informacion de la empresa."
                },
                "nombre":
                {
                    "type": "string",
                    "description": "Guarda el nombre de la empresa"
                },
                "ubicacion":
                {
                    "type": "string",
                    "description": "Guarda la ubicacion de la empresa"
                },
                "correo":
                {
                    "type": "string",
                    "description": "Guarda el correo de la empresa"
                },
                "director":
                {
                    "type": "string",
                    "description": "Guarda el nombre del director de la empresa"
                },
                "descripcion":
                {
                    "type": "string",
                    "description": "Guarda una descripcion de la empresa."
                }
            }
        }

    }
}